"""
Claude→Kimi dispatch helper.

Hands off a code-generation task to Kimi K2.6 via Mercury (which routes through
Nous Portal).  Used by Claude Code in the orchestration workflow:

    Claude (this session) writes a spec + tests
        → kimi_dispatch.py sends the task to Kimi
        → Kimi returns code
        → Claude validates + commits

Usage:
    python tools/kimi_dispatch.py --task <path> [--out <path>] [--model <id>]

    --task   Path to a markdown file containing the spec/instructions.  Required.
    --out    Path to write the model's response.  Default: prints to stdout.
    --model  Override model.  Default: moonshotai/kimi-k2.6.  Other useful:
             - nousresearch/hermes-4-405b  (planner / reasoning)
             - moonshotai/kimi-k2-thinking (longer reasoning, slower)

    --planner   Convenience flag: use Hermes 4 405B instead of Kimi.

API key: read from $NOUS_API_KEY (set via setx).  This script also falls back
to reading the persisted user-env value via Windows registry, so it works in
any shell on this machine.

This script intentionally does NOT call Mercury's CLI — Mercury's `-z` mode
adds banners and is harder to script reliably.  Going direct to the OpenAI-
compatible Nous inference URL is faster and more deterministic.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import urllib.request
import urllib.error
from pathlib import Path

if sys.stdout.encoding and sys.stdout.encoding.lower() != "utf-8":
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass

NOUS_BASE_URL = "https://inference-api.nousresearch.com/v1"

DEFAULT_MODEL_CODER   = "moonshotai/kimi-k2.6"
DEFAULT_MODEL_PLANNER = "nousresearch/hermes-4-405b"

CODER_SYSTEM_PROMPT = (
    "You are Kimi K2.6 acting as a senior software engineer in a Claude-led "
    "code-review workflow. You will be given a spec written by Claude Sonnet "
    "(the tech lead).  Your job: produce production-quality code that exactly "
    "matches the spec.\n\n"
    "Conventions:\n"
    "  - Match existing code style (Conventional Commits, no emojis, no "
    "    'Generated by' comments, terse docstrings only when the *why* is "
    "    non-obvious).\n"
    "  - Write tests alongside the implementation.  Pytest convention.\n"
    "  - Output only the code blocks, each prefixed by `### FILE: <path>` so a "
    "    parser can split them apart.  No prose between code blocks unless "
    "    explicitly requested in the spec.\n"
    "  - If the spec has gaps that *must* be filled to compile/run, fill them "
    "    minimally and call them out at the end under `### NOTES:`.\n"
    "  - Never invent file paths.  Use only paths the spec or context refers to."
)

PLANNER_SYSTEM_PROMPT = (
    "You are Hermes 4 405B acting as the planner for a Claude-led engineering "
    "workflow.  Given a goal, output a numbered, atomic list of tasks ready "
    "to dispatch one-at-a-time to a code-generation model (Kimi K2.6).  Each "
    "task is one file or one test.  No fluff."
)


def _resolve_api_key() -> str:
    """Read NOUS_API_KEY from current env, else from persisted Windows user env."""
    key = os.environ.get("NOUS_API_KEY", "").strip()
    if key:
        return key
    # Fallback: query persisted user env via reg query (Windows)
    if os.name == "nt":
        try:
            import subprocess
            out = subprocess.check_output(
                ["reg", "query", "HKCU\\Environment", "/v", "NOUS_API_KEY"],
                stderr=subprocess.DEVNULL,
            ).decode("utf-8", errors="replace")
            for line in out.splitlines():
                if "NOUS_API_KEY" in line and "REG_SZ" in line:
                    return line.split("REG_SZ", 1)[1].strip()
        except Exception:
            pass
    raise SystemExit(
        "NOUS_API_KEY not set.  Either run: setx NOUS_API_KEY \"sk-...\" "
        "in a PowerShell window and restart your shell, or pass it inline."
    )


def _post_chat(api_key: str, model: str, messages: list[dict],
               max_tokens: int = 8192, temperature: float = 0.2) -> dict:
    body = json.dumps({
        "model":       model,
        "messages":    messages,
        "max_tokens":  max_tokens,
        "temperature": temperature,
        "stream":      False,
    }).encode("utf-8")
    req = urllib.request.Request(
        f"{NOUS_BASE_URL}/chat/completions",
        data=body,
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type":  "application/json",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=300) as resp:
            return json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as e:
        body = e.read().decode("utf-8", errors="replace")
        raise SystemExit(f"HTTP {e.code} from Nous Portal: {body[:600]}")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--task",    required=True, help="Path to markdown spec file")
    ap.add_argument("--out",     default=None,   help="Path to write response (default stdout)")
    ap.add_argument("--model",   default=None,   help="Model override")
    ap.add_argument("--planner", action="store_true",
                    help="Use Hermes 4 405B planner system prompt")
    ap.add_argument("--max-tokens", type=int, default=8192)
    ap.add_argument("--temperature", type=float, default=0.2)
    args = ap.parse_args()

    spec_path = Path(args.task)
    if not spec_path.exists():
        raise SystemExit(f"Spec file not found: {spec_path}")

    spec = spec_path.read_text(encoding="utf-8")
    api_key = _resolve_api_key()

    if args.planner:
        model = args.model or DEFAULT_MODEL_PLANNER
        system = PLANNER_SYSTEM_PROMPT
    else:
        model = args.model or DEFAULT_MODEL_CODER
        system = CODER_SYSTEM_PROMPT

    print(f"→ dispatching to {model} ({len(spec)} chars of spec)", file=sys.stderr)
    resp = _post_chat(
        api_key, model,
        [
            {"role": "system", "content": system},
            {"role": "user",   "content": spec},
        ],
        max_tokens=args.max_tokens,
        temperature=args.temperature,
    )

    choice = resp.get("choices", [{}])[0]
    content = choice.get("message", {}).get("content", "")
    usage = resp.get("usage", {})
    cost = usage.get("cost", 0.0)
    print(
        f"← {usage.get('prompt_tokens', '?')} in / "
        f"{usage.get('completion_tokens', '?')} out  "
        f"(~${cost:.4f})", file=sys.stderr,
    )

    if args.out:
        Path(args.out).write_text(content, encoding="utf-8")
        print(args.out)
    else:
        print(content)


if __name__ == "__main__":
    main()
